### ISSUE TITLE
installation of expect

### ISSUE THREAD

**Issue by fjbsaper** [ibm-messaging/mq-appliance#3]
Expect is very difficult to get hold of (Windows as well as Linux). I would not mind seeing a little bit more information on how to install it than just the link to the Expect "home page" which holds 3 links 1 of which is invalid.
A little bit more direction here would go a long way...

**Comment by samgoulden28** [comment]
Depending on your platform, you can use a package manager such as yum or apt-get to install expect (If you are on Linux).

On windows, you can install it using ActiveTcl, via its package manager called teacup. Find instructions for that here:

http://wiki.tcl.tk/17305
